'use client'
import { Inter } from "next/font/google";
import "./globals.css";
import { useRouter } from "next/navigation";
const inter = Inter({ subsets: ["latin"] });
// export const metadata = {
//   title: "K6 management",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const router = useRouter();
  if(!localStorage.getItem('k6')) router.replace('http://localhost:3000/login')
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
