import AddShape from "../components/AddShape";

async function PressPage() {
  const getShapes = async () => {
    const response = await fetch("http://localhost:3000/press/api");
    return await response.json();
  };
  const generateKeysArr = (target) => {
    const keys = Object.keys(target);
    const length = keys.length;
    return keys.slice(1, length - 1);
  };
  const shapes = await getShapes();
  const shapeKeys = generateKeysArr(shapes[0]);
  return (
    <div>
      <h1>Press Page</h1>
      <div id="press_shapes">
        {shapes &&
          shapes.map((shape, index) => {
            return <div key={index}>{shape.name}</div>;
          })}
      </div>
      <AddShape shapeKeys={shapeKeys} />
      {/* //! minus 2 because keys (id, __v) do not concern the user. __v should not be sent to the browser. id is generated by mongoose */}
    </div>
  );
}

export default PressPage;
